version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - run:
          command: ruby --version
      - run:
          command: gem --version
      - run:
          command: bundler --version

workflows:
  version: 2
  workflow:
    jobs:
      - build